In [1]:
import pandas as pd
test_by_user  = pd.read_csv("/kaggle/input/datahotel/test_by_user_695.csv")
test_by_user

URL Hotel Location  HotelID  \
0    https://www.booking.com/hotel/vn/dalat-wind.vi...   Đà Lạt     4064   
1    https://www.booking.com/hotel/vn/raon-valley-v...   Đà Lạt     3890   
2    https://www.booking.com/hotel/vn/raon-valley-v...   Đà Lạt     3890   
3    https://www.booking.com/hotel/vn/raon-villa-da...   Đà Lạt     3288   
4    https://www.booking.com/hotel/vn/wasabi-house....   Đà Lạt     4388   
..                                                 ...      ...      ...   
690  https://www.booking.com/hotel/vn/vinpearl-hue-...      Huế     2403   
691  https://www.booking.com/hotel/vn/senna-hue.vi....      Huế     4443   
692  https://www.booking.com/hotel/vn/na-na-homesta...      Huế     2259   
693  https://www.booking.com/hotel/vn/nana-2-homest...      Huế     3735   
694  https://www.booking.com/hotel/vn/phuong-loan-h...      Huế     3845   

                             Name Hotel  \
0               Dalat Wind Deluxe Hotel   
1                            Raon Villa   
2                            Raon Villa   
3                            Raon Hotel   
4    Wasabi House - Phương Anh Homestay   
..                                  ...   
690                  Melia Vinpearl Hue   
691                     Senna Hue Hotel   
692               Nana Homestay & Villa   
693                     Nana 2 Homestay   
694                         Amona Hotel   

                                          Descriptions  \
0    Tọa lạc tại thành phố Đà Lạt, cách Hồ Xuân Hươ...   
1    Tọa lạc tại thành phố Đà Lạt, cách CLB chơi go...   
2    Tọa lạc tại thành phố Đà Lạt, cách CLB chơi go...   
3    Tọa lạc tại thành phố Đà Lạt, cách Công viên Y...   
4    Tọa lạc ở thành phố Đà Lạt, cách Quảng trường ...   
..                                                 ...   
690  Trong số các tiện nghi của chỗ nghỉ này có nhà...   
691  Khách sạn 5 sao này cũng có WiFi miễn phí, vườ...   
692  Nằm cách Chợ Đông Ba 1,4 km, Nana Homestay & V...   
693  Tọa lạc tại thành phố Huế với Chợ Đông Ba và C...   
694  Khách sạn 2 sao này cách Chợ Đông Ba 800 m và ...   

                                               Address  UserID   User  Rating  
0    Lot R2 03-04. Golf Valley, Ward 2, Đà Lạt, Viê...    1284   Tran       5  
1       44D Trần Khánh Dư, Phường 8, Đà Lạt, Việt Nam    1284   Tran       6  
2       44D Trần Khánh Dư, Phường 8, Đà Lạt, Việt Nam    1284   Tran       7  
3        42 Tô Hiến Thành, Phường 3, Đà Lạt, Việt Nam    1284   Tran       8  
4               20/2 Phan Như Thạch, Đà Lạt, Việt Nam    1284   Tran       7  
..                                                 ...     ...    ...     ...  
690              50A Hung Vuong Street, Huế, Việt Nam     335  Thanh      10  
691  7 Nguyễn Tri Phương, phường Phú Hội, Tp Huế 7 ...     335  Thanh       8  
692         26/1/147 Phan Đình Phùng 3, Huế, Việt Nam     335  Thanh       6  
693  14/42 Nguyễn Công Trứ, Phường Phú Hội, Huế, Vi...     335  Thanh       5  
694        11 Nguyen Cong Tru, Phu Hoi, Huế, Việt Nam     335  Thanh       5  

[695 rows x 9 columns]

# Best GHRS Present

In [2]:
import pickle
with open('/kaggle/input/best-ghrs-present/best_ghrs.pkl', 'rb') as file:
    ghrs = pickle.load(file)
ghrs

array([[5.99997   , 5.4999725 , 7.99992   , ..., 5.93996596, 6.26807194,
        5.94337718],
       [8.1       , 7.        , 8.22222222, ..., 7.        , 6.        ,
        9.57142857],
       [0.        , 5.99994   , 7.12498219, ..., 6.95210695, 6.67677801,
        9.        ],
       ...,
       [8.1       , 7.        , 8.22222222, ..., 7.        , 6.        ,
        9.57142857],
       [8.1       , 7.        , 8.22222222, ..., 7.        , 6.        ,
        9.57142857],
       [7.06665783, 7.03702922, 7.4166574 , ..., 7.26025395, 7.76944915,
        8.        ]])

In [3]:
ghrs.shape

(6471, 4506)

# GLocalK

In [4]:
import pickle
with open('/kaggle/input/model-rating-matrix/result_user_rating_predict_glocalK.pkl', 'rb') as file:
    glocalk = pickle.load(file)
glocalk

array([[4.65004707, 4.67393401, 4.64333052, ..., 6.86745366, 6.64574338,
        3.39768983],
       [4.65631342, 4.68011774, 4.64945116, ..., 6.87686377, 6.65470868,
        3.4021279 ],
       [4.65633006, 4.68020746, 4.64937355, ..., 6.87707294, 6.6549985 ,
        3.40223258],
       ...,
       [4.63209989, 4.65576675, 4.62519317, ..., 6.84121955, 6.62021705,
        3.38463048],
       [4.65481414, 4.67848771, 4.64782904, ..., 6.87468036, 6.65271307,
        3.4008711 ],
       [4.6534856 , 4.677118  , 4.64645821, ..., 6.87265031, 6.65073691,
        3.39987837]])

In [5]:
import numpy as np

In [6]:
glocalk = np.transpose(glocalk)
glocalk.shape

(6471, 4506)

# Tính trung bình 2 matrix 

In [7]:
user_rating_new = glocalk*0.4+ghrs*0.6
user_rating_new

array([[5.46000083, 5.16250887, 6.66248402, ..., 5.41681953, 5.62276882,
        5.42742055],
       [6.7295736 , 6.0720471 , 6.80541632, ..., 6.0623067 , 5.47139508,
        7.61370434],
       [1.85733221, 5.45974446, 6.13473873, ..., 6.02134144, 5.86519842,
        7.25858329],
       ...,
       [7.60698146, 6.95074551, 7.68416251, ..., 6.93648782, 6.34987214,
        8.49191726],
       [7.51829735, 6.86188347, 7.59533273, ..., 6.84808682, 6.26108523,
        8.40315191],
       [5.59907063, 5.58306869, 5.81088747, ..., 5.71000456, 6.02201793,
        6.15995135]])

In [8]:
user_rating_new.shape

(6471, 4506)

# Evaluating

In [9]:
ground_truth = test_by_user['Rating'].values
ground_truth[:10]

array([5, 6, 7, 8, 7, 6, 8, 6, 6, 7])

In [10]:
def get_list_4test(user_rating_matrix, test):
    test_list = []
    for i in range(test.shape[0]):
        rating = user_rating_matrix[test.iloc[i]['UserID'] - 1][test.iloc[i]['HotelID'] - 1]
        test_list.append(rating)
    
    return test_list

In [11]:
test_list = get_list_4test(user_rating_new, test_by_user)
test_list[:10]

[7.203928386421305,
 7.866323761832398,
 7.866323761832398,
 7.365146269842007,
 7.148766289702774,
 7.264089053655466,
 6.558393091746174,
 7.426932400429088,
 7.426932400429088,
 6.525220503129039]

In [12]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(ground_truth , test_list)
print('MSE =',mse)

MSE = 2.2866677211135276


In [13]:
import math
rmse = math.sqrt(mse)
print('RMSE =',rmse)   

RMSE = 1.5121731782813526


In [14]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(ground_truth , test_list)
print('MAE =',mae)

MAE = 1.3067572188849594


In [15]:
MAX = max(test_by_user['Rating'].tolist())
MIN = min(test_by_user['Rating'].tolist())

nmae = mae/(MAX-MIN)
print('NMAE =',nmae)

NMAE = 0.2177928698141599


In [16]:
# Sắp xếp danh sách dự đoán và ground truth
from sklearn.metrics import ndcg_score
sorted_idx = np.argsort(test_list)[::-1]  # Sắp xếp giảm dần
sorted_ground_truth = ground_truth[sorted_idx]

# Tính toán NDCG
ndcg = ndcg_score([ground_truth], [sorted_ground_truth])
print(f"NDCG: {ndcg}")

NDCG: 0.9513687351524676


# Lưu lại ma trận predict rating

In [17]:
user_rating_new = user_rating_new.astype(np.float16)

In [18]:
user_rating_new

array([[5.46 , 5.164, 6.664, ..., 5.418, 5.62 , 5.426],
       [6.73 , 6.07 , 6.805, ..., 6.062, 5.473, 7.613],
       [1.857, 5.46 , 6.133, ..., 6.02 , 5.863, 7.258],
       ...,
       [7.605, 6.95 , 7.684, ..., 6.938, 6.35 , 8.49 ],
       [7.52 , 6.863, 7.594, ..., 6.848, 6.26 , 8.41 ],
       [5.598, 5.582, 5.812, ..., 5.71 , 6.023, 6.16 ]], dtype=float16)

In [19]:
import pickle
import gzip

# Specify the file name
file_name = 'ensemble_model.pkl.gz'

# Open the file with gzip compression
with gzip.open(file_name, 'wb') as file:
    pickle.dump(user_rating_new, file)


In [20]:
# Open the file with gzip decompression
with gzip.open('/kaggle/working/ensemble_model.pkl.gz', 'rb') as file:
    loaded_data = pickle.load(file)
    
loaded_data

array([[5.46 , 5.164, 6.664, ..., 5.418, 5.62 , 5.426],
       [6.73 , 6.07 , 6.805, ..., 6.062, 5.473, 7.613],
       [1.857, 5.46 , 6.133, ..., 6.02 , 5.863, 7.258],
       ...,
       [7.605, 6.95 , 7.684, ..., 6.938, 6.35 , 8.49 ],
       [7.52 , 6.863, 7.594, ..., 6.848, 6.26 , 8.41 ],
       [5.598, 5.582, 5.812, ..., 5.71 , 6.023, 6.16 ]], dtype=float16)